version: "3.3"

services:
  streamlit-iris:
    restart: unless-stopped
    build: .
    image: mlrun-ai-apps
    container_name: mlrun-ai-apps
    environment:
      - PORT=${PORT:-8501}
    ports:
      - ${PORT:-8501}:${PORT:-8501}
