version: "3.3"

services:
  streamlit-iris:
    restart: unless-stopped
    build: .
    image: nschenone/streamlit-iris
    container_name: streamlit-iris
    environment:
      - PORT=${PORT:-8501}
    ports:
      - ${PORT:-8501}:${PORT:-8501}
